.PHONY: clean All

All:
	@echo "----------Building project:[ NumCplusplus - Debug ]----------"
	@cd "NumCplusplus" && "$(MAKE)" -f  "NumCplusplus.mk"
clean:
	@echo "----------Cleaning project:[ NumCplusplus - Debug ]----------"
	@cd "NumCplusplus" && "$(MAKE)" -f  "NumCplusplus.mk" clean
